### ISSUE TITLE
No module named gui.api.backend

### ISSUE THREAD

**Issue by rameez707** [victorgabr/pps#2]

**Comment by victorgabr** [comment]
Could you add provide more details?

Could you provide you full terminal output?

It seems to a relative import problem. 

You may change this line for: pyplanscoring.gui.api.backend

**Comment by rameez707** [comment]
![Untitled](https://user-images.githubusercontent.com/55708510/65527222-c2f54900-df0b-11e9-83b1-547b58e47423.png)

**Comment by rameez707** [comment]
This issue comes when i was using Anaconda 2 and python 2.7 but if i use python 3.6 it return error No module named 'PySide' and i am unable to install pyside because its supported till python version 3.4

**Comment by victorgabr** [comment]
Python 2 will be deprecated soon, I do not recommend using it.

PPS GUI relies on PySide, but the package "pyplanscoring" no.

A workaround for it is create a anaconda environment with python 3.6 or greater.

and install pyside from conda-forge channel by:

`conda install -c conda-forge numpy numba pandas xlsxwriter scipy matplotlib  joblib pyside pillow quantities xlrd pyinstaller
`

Thanks,
Victor

**Comment by rameez707** [comment]
![Untitled2](https://user-images.githubusercontent.com/55708510/65704473-0da7ca00-e0a0-11e9-887f-8595d1cf6df5.png)

**Comment by rameez707** [comment]
Using Anaconda3-4.3.1 and python 3.6.0

**Comment by rameez707** [comment]
Still having issue on install pyside

**Comment by victorgabr** [comment]
Uninstall your current anaconda.

install:
[Miniconda](https://docs.conda.io/en/latest/miniconda.html)

It is a minimal python installation without scientific packages.

create a new environment:

`conda create -n py36 python=3.6`

Activate the environment:

`conda activate py36`

Then run the command:

`conda install -c conda-forge numpy numba pandas xlsxwriter scipy matplotlib joblib pyside pillow quantities xlrd pyinstaller
`

**Comment by rameez707** [comment]
![Untitled3](https://user-images.githubusercontent.com/55708510/65783386-2203c980-e169-11e9-9d54-bfc28b079b3e.png)

**Comment by rameez707** [comment]
![Untitled4](https://user-images.githubusercontent.com/55708510/65783431-3051e580-e169-11e9-9bee-4be6fb90511a.png)

**Comment by rameez707** [comment]
Still got same PySide Error

**Comment by victorgabr** [comment]
It is an anaconda/miniconda issue, It used to work before.
As I said, PySide is only a hard dependency if you need to use the GUI.

pyplanscoring package does not need, it could be used as command-line/script usage as explained on the docs.

But you could install the dependencies manually from here (PySide and others from here):

[Win64 Dependencies](https://www.lfd.uci.edu/~gohlke/pythonlibs/)

**Comment by rameez707** [comment]
Thanks a lot.
I accomplished it by installing Miniconda3-4.3.31-Windows-x86_64

conda create -n py36 python=3.6.0

activate py36

conda install -c conda-forge pyside

conda install -c conda-forge numpy numba pandas xlsxwriter scipy joblib pyside quantities xlrd pyinstaller

conda install -c conda-forge pillow=3.4.2

conda install cudatoolkit

unable to install matplotlib=>2.0.0 from command line due to conflict so install it from pycharm project interpreter
