### ISSUE TITLE
Collimator Angle in DVH data 

### ISSUE THREAD

**Issue by rameez707** [victorgabr/pps#4]
Is Collimator Angle exist in dvh data? Where can i find it?

**Comment by victorgabr** [comment]
The collimator angle is not part of the DVH data. You can find it by parsing Dicom RTPLAN data:

[RTPLAN](http://dicom.nema.org/dicom/2013/output/chtml/part03/sect_A.20.html)

[COLLIMATOR](https://dicom.innolitics.com/ciods/rt-beams-treatment-record/rt-beams-session-record/30080020/30080040/300a0120
)
From:

[DICOM_READER](https://github.com/victorgabr/pps/blob/master/pyplanscoring/core/dicom_reader.py)

The method:

GetSOPClassUID() gives you the type of DICOM file you are reading.

There is a method called "GetPlan()" that gives you a dictionary with treatment plan parameters.
