### ISSUE TITLE
Get possible query options

### ISSUE THREAD

**Issue by rameez707** [victorgabr/pps#6]
Is theirs a way to get list of all possible query value according to Structure

**Comment by victorgabr** [comment]
So there is no way to get ALL possible query options.
A DVH query is not something that is inside a DICOM file, it is something that must be provided by the user. 
This doc provides the standard:
[9. Recommendations for Dose Volume Histogram Metrics](https://www.aapm.org/pubs/reports/RPT_263.pdf)
This doc summarizes how they must be provided.
[Mayo Format](https://github.com/rexcardan/ESAPIX/blob/master/DocFX/articles/mayoFormat.md
